### ISSUE TITLE
The chat is bugged when gamemaster text something .

### ISSUE THREAD

**Issue by mmorpg4all** [azerothcore/mod-world-chat#14]
If i use .chat from my gamemaster account , the text have some lines like | | | | betwen words.

Check the photo (https://i.ibb.co/Ytrwq3B/gmchat.png)

Who can solve this ? Thanks

**Comment by wizzymore** [comment]
Hi @mmorpg4all, i don't think that this is the correct behaviour but these is nothing related to the module.

To replicate the same effect on what you are showing in your image try to simply use:
```
.gm chat on
Type in chat: TTTTTT
```

This problem is something related to the font because of the BLIZZ image.
