### ISSUE TITLE
A little bit of advice

### ISSUE THREAD

**Issue by mpfans** [azerothcore/mod-world-chat#15]
1.When a player is chatting in the world, other players can't directly click on his name to whisper.
2.It is suggested to add a function: display the level of the speaker in the world chat

**Comment by wizzymore** [comment]
Hi @mpfans, The first request, can't really be done without core modifications.
2. You can modify in what format it is shown right here:
https://github.com/azerothcore/mod-world-chat/blob/1af580b8c98227b4e81e92b07453c9436bd89997/src/WorldChat.cpp#L149

**Comment by mpfans** [comment]
> Hi @mpfans, The first request, can't really be done without core modifications.
> 2. You can modify in what format it is shown right here:
> https://github.com/azerothcore/mod-world-chat/blob/1af580b8c98227b4e81e92b07453c9436bd89997/src/WorldChat.cpp#L149

tyvm.  If you can't click the character name directly to enter the whisper, then no player is willing to use the chat in this world

**Comment by wizzymore** [comment]
Hi @mpfans,

I will try to look into this and make this work, your idea is great and it would really be nice to have this working.
Maybe even add a chat channel to be used instead of always typing .chat before your message

**Comment by wizzymore** [comment]
Good news!

It seems there is a method by adding the chat format |Hplayer:NAME|hNAME|h
I will give you a PR to test and let me know if this works with you.

**Comment by wizzymore** [comment]
Hi @mpfans,

You can try world chat version 2.0 on my repo:
https://github.com/wizzymore/mod_world_chat/

To use the chat, now you can /join World and talk like that, or, chat as you used to, using .chat $text ( .chata and .chath still works for gm's when CrossFaction is false so he can talk and see all the messages )
Also, now you can click on a name of a player for whisper or right click to open menu:
https://prnt.sc/waufqw

**Comment by FrancescoBorzi** [comment]
good job @wizzymore

**Comment by mpfans** [comment]
> Hi @mpfans,
> 
> You can try world chat version 2.0 on my repo:
> https://github.com/wizzymore/mod_world_chat/
> 
> To use the chat, now you can /join World and talk like that, or, chat as you used to, using .chat $text ( .chata and .chath still works for gm's when CrossFaction is false so he can talk and see all the messages )
> Also, now you can click on a name of a player for whisper or right click to open menu:
> https://prnt.sc/waufqw

I'll test it and give feedback!

**Comment by mpfans** [comment]
> Hi @mpfans, The first request, can't really be done without core modifications.
> 2. You can modify in what format it is shown right here:
> https://github.com/azerothcore/mod-world-chat/blob/1af580b8c98227b4e81e92b07453c9436bd89997/src/WorldChat.cpp#L149-L181
