### ISSUE TITLE
Bug: Failed to Compile with latest build

### ISSUE THREAD

**Issue by Viskus** [azerothcore/mod-world-chat#31]
### Current Behaviour

When trying to compile with latest build there is an error.

WorldChat.cpp:265:41: fatal error: no matching constructor for initialization of 'std::vector<ChatCommand>' (aka 'vector<Acore::ChatCommands::ChatCommandBuilder>')
        static std::vector<ChatCommand> wcCommandTable =

### Expected Behaviour

Should compile OK

### Steps to reproduce the problem

1. compile server with worldchat module.

### AC rev. hash/commit

WorldChat.cpp:265:41: fatal error: no matching constructor for initialization of 'std::vector<ChatCommand>' (aka 'vector<Acore::ChatCommands::ChatCommandBuilder>')
        static std::vector<ChatCommand> wcCommandTable =

### Operating system

Ubuntu

**Comment by qq462518439** [comment]
+1

**Comment by xSparky911x** [comment]
+1
