### ISSUE TITLE
As gamemaster read what you wrote in the chat of the other faction

### ISSUE THREAD

**Issue by Selyria** [azerothcore/mod-world-chat#5]
So the fix with the as an alliance gm in horde chat writing goes super work

if it were still possible to see what you wrote in the Horde Chat as an Alliance Gamemaster it would be perfect

If it were still possible for a Horde Gamemaster to see what you wrote in the Alliance Chat, it would be perfect.

<img width="2032" alt="Unbenannt" src="https://user-images.githubusercontent.com/179698/58594765-e0244e80-826e-11e9-8386-dd13b3cfb46e.PNG">

**Comment by talamortis** [comment]
Hi is it possible for you to test something for me, I also believe this Is a good idea
at this line https://github.com/azerothcore/mod-world-chat/blob/master/src/WorldChat.cpp#L221

change too

` if (WorldChat[guid2].chat == 1 && (target->GetTeamId() == TEAM_HORDE || target->IsGM()))`

and then do the same for the alliance

https://github.com/azerothcore/mod-world-chat/blob/master/src/WorldChat.cpp#L274

 if (WorldChat[guid2].chat == 1 && (target->GetTeamId() == TEAM_ALLIANCE || target->IsGM()))

**Comment by talamortis** [comment]
@milestorme  are you able to test the above if this works ill do a PR as I am unable to test

**Comment by milestorme** [comment]
Build errors
`[ 94%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-world-chat-master/src/WorldChat.cpp.o
[ 94%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-vas-autobalance/src/VASAutoBalance.cpp.o
[ 94%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-transmog/src/transmog_scripts.cpp.o
/var/michael/corerocket/azerothcore-wotlk/modules/mod-world-chat-master/src/WorldChat.cpp:221:93: error:
      no member named 'IsGM' in 'Player'
            if (WorldChat[guid2].chat == 1 && (target->GetTeamId() == TEAM_HORDE || target->IsGM()))
                                                                                    ~~~~~~  ^
/var/michael/corerocket/azerothcore-wotlk/modules/mod-world-chat-master/src/WorldChat.cpp:274:96: error:
      no member named 'IsGM' in 'Player'
  ...if (WorldChat[guid2].chat == 1 && (target->GetTeamId() == TEAM_ALLIANCE || target->IsGM()))
                                                                                ~~~~~~  ^
[ 94%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-transmog/src/Transmogrification.cpp.o
2 errors generated.
`

**Comment by milestorme** [comment]
Added you as a collaborator @talamortis on my fork make the changes there and I’ll test again
